#ifndef TESTS_FAKES_APP_CONFIG_H
#define TESTS_FAKES_APP_CONFIG_H

#define HIP_CONTROL_ENABLE 1

#define MOTOR_LINK_CAN_LEFT_ID 0x01U
#define MOTOR_LINK_CAN_RIGHT_ID 0x02U

#define HIP_CAN_NODE_LEFT 0x03U
#define HIP_CAN_NODE_RIGHT 0x04U

#define HIP_CMD_PERIOD_MS 10U
#define HIP_TELEM_PERIOD_MS 20U
#define HIP_HEARTBEAT_PERIOD_MS 200U
#define HIP_TELEM_TIMEOUT_MS 200U
#define HIP_LIMIT_DEBOUNCE_SAMPLES 4U

#define HIP_THETA_MIN_DEG 23.95f
#define HIP_THETA_MAX_DEG 61.04f

#define HIP_HEIGHT_SLEW_MPS 0.2f
#define HIP_VEL_MAX_REV_S 0.5f
#define HIP_TORQUE_MAX_NM 20.0f
#define HIP_STIFFNESS_N_M_DEFAULT 800.0f
#define HIP_DAMPING_N_S_M_DEFAULT 80.0f
#define HIP_HEIGHT_DEFAULT_M 0.5f

#define HIP_BEHAVIOR_CROUCH_MS 150U
#define HIP_BEHAVIOR_IMPULSE_MS 100U
#define HIP_BEHAVIOR_FLIGHT_MS 200U
#define HIP_BEHAVIOR_LANDING_MS 200U

#define HIP_CROUCH_DEPTH_M 0.05f
#define HIP_IMPULSE_HEIGHT_M 0.08f
#define HIP_IMPULSE_LIFTOFF_VEL_MPS 0.1f
#define HIP_LIFTOFF_ACCEL_G 0.7f
#define HIP_LANDING_ACCEL_G 1.2f

#define HIP_CROUCH_RATE_MPS 0.15f
#define HIP_IMPULSE_RATE_MPS 0.3f

#define HIP_GROUND_STIFFNESS_N_M 600.0f
#define HIP_GROUND_DAMPING_N_S_M 60.0f
#define HIP_FLIGHT_STIFFNESS_N_M 200.0f
#define HIP_FLIGHT_DAMPING_N_S_M 20.0f
#define HIP_LANDING_STIFFNESS_N_M 1000.0f
#define HIP_LANDING_DAMPING_N_S_M 120.0f

#define HIP_WHEEL_FF_PITCH_GAIN 0.5f

#define HIP_WHEEL_SCALE_IMPULSE 0.7f
#define HIP_WHEEL_SCALE_FLIGHT 0.3f
#define HIP_WHEEL_SCALE_LANDING 0.6f

#define HIP_STALL_ERR_REV 0.02f
#define HIP_STALL_TIMEOUT_MS 500U
#define HIP_RECOVERY_TIMEOUT_MS 2000U

#define HIP_HAS_ENABLE_PIN 0

#endif /* TESTS_FAKES_APP_CONFIG_H */
