#ifndef IMU_BMM150_CONFIG_H
#define IMU_BMM150_CONFIG_H

#include "bmm150_defs.h"

/* BMM150 bring-up configuration */
#define BMM150_CFG_PWR_MODE        BMM150_POWERMODE_NORMAL
#define BMM150_CFG_PRESET_MODE     BMM150_PRESETMODE_REGULAR
#define BMM150_CFG_DRDY_POLARITY   BMM150_ACTIVE_HIGH_POLARITY
#define BMM150_CFG_INT_POLARITY    BMM150_ACTIVE_HIGH_POLARITY
#define BMM150_CFG_INT_LATCH       BMM150_NON_LATCHED

#define BMM150_CFG_FALLBACK_POLL_MS 0U
#define BMM150_CFG_DMA_TIMEOUT_MS  0U

#endif /* IMU_BMM150_CONFIG_H */

