#ifndef IMU_BMI270_CONFIG_H
#define IMU_BMI270_CONFIG_H

#include "bmi2_defs.h"

/* BMI270 bring-up configuration */
#define BMI270_CFG_ACC_ODR         BMI2_ACC_ODR_400HZ
#define BMI270_CFG_ACC_RANGE       BMI2_ACC_RANGE_4G
#define BMI270_CFG_ACC_BWP         BMI2_ACC_NORMAL_AVG4
#define BMI270_CFG_ACC_FILTER_PERF BMI2_PERF_OPT_MODE

#define BMI270_CFG_GYR_ODR         BMI2_GYR_ODR_800HZ
#define BMI270_CFG_GYR_RANGE       BMI2_GYR_RANGE_500
#define BMI270_CFG_GYR_BWP         BMI2_GYR_NORMAL_MODE
#define BMI270_CFG_GYR_NOISE_PERF  BMI2_POWER_OPT_MODE
#define BMI270_CFG_GYR_FILTER_PERF BMI2_PERF_OPT_MODE

#define BMI270_CFG_INT_LVL         BMI2_INT_ACTIVE_LOW
#define BMI270_CFG_INT_OD          BMI2_INT_PUSH_PULL
#define BMI270_CFG_INT_LATCH        BMI2_INT_NON_LATCH

#define BMI270_CFG_READ_WRITE_LEN  32U

#define BMI270_CFG_FALLBACK_POLL_MS 0U
#define BMI270_CFG_DMA_TIMEOUT_MS   0U

#endif /* IMU_BMI270_CONFIG_H */
