// Generated by tools/lqr_lut_to_header.py
// Source: lqr_lut.csv
// Generated: 2026-02-11T18:54:23

#ifndef CONTROL_LQR_LUT_DATA_H
#define CONTROL_LQR_LUT_DATA_H

#define LQR_LUT_SIZE 7

static const float kHipLut[LQR_LUT_SIZE] = {
    -0.270000f,
    -0.162500f,
    -0.055000f,
    0.052500f,
    0.160000f,
    0.267500f,
    0.375000f,
};

static const float kLqrLut[LQR_LUT_SIZE][4] = {
    { -5.000000f, -35.000000f, -400.000000f, -24.000000f },
    { -5.000000f, -35.000000f, -400.000000f, -24.000000f },
    { -5.000000f, -35.000000f, -400.000000f, -24.000000f },
    { -5.000000f, -35.000000f, -400.000000f, -24.000000f },
    { -5.000000f, -35.000000f, -400.000000f, -24.000000f },
    { -5.000000f, -35.000000f, -400.000000f, -24.000000f },
    { -5.000000f, -35.000000f, -400.000000f, -24.000000f },
};

static const float kThetaEq[LQR_LUT_SIZE] = {
    -0.145000f,
    -0.115000f,
    -0.070000f,
    -0.095000f,
    0.025000f,
    0.010000f,
    -0.100000f,
};

static const float kUEq[LQR_LUT_SIZE] = {
    0.000000f,
    0.000000f,
    0.000000f,
    0.000000f,
    0.000000f,
    0.000000f,
    0.000000f,
};

#endif /* CONTROL_LQR_LUT_DATA_H */
