// Generated by tools/lqr_lut_to_header.py
// Source: lqr_lut.csv
// Generated: 2026-02-15T19:07:25

#ifndef CONTROL_LQR_LUT_DATA_H
#define CONTROL_LQR_LUT_DATA_H

#define LQR_LUT_SIZE 7

static const float kHipLut[LQR_LUT_SIZE] = {
    -0.270000f,
    -0.162500f,
    -0.055000f,
    0.052500f,
    0.160000f,
    0.267500f,
    0.375000f,
};

static const float kLqrLut[LQR_LUT_SIZE][4] = {
    { -1.000000f, 8.230978f, 21.781541f, 2.573736f },
    { -0.433114f, 8.698382f, 17.328331f, 1.423794f },
    { -0.262171f, 8.214888f, 10.131417f, 0.649205f },
    { -0.316228f, 8.922042f, 30.362171f, 1.134909f },
    { -0.775000f, 9.308903f, 47.248929f, 1.441295f },
    { -7.750000f, 9.553590f, 60.988466f, 1.637010f },
    { -0.316228f, 9.679192f, 68.834250f, 1.755285f },
};

static const float kThetaEq[LQR_LUT_SIZE] = {
    -0.236509f,
    -0.206105f,
    -0.169367f,
    -0.129327f,
    -0.100697f,
    -0.078027f,
    -0.065696f,
};

static const float kUEq[LQR_LUT_SIZE] = {
    0.000000f,
    0.000000f,
    0.000000f,
    0.000000f,
    0.000000f,
    -0.000000f,
    -0.000000f,
};

#endif /* CONTROL_LQR_LUT_DATA_H */
