// Generated by tools/lqr_lut_to_header.py
// Source: lqr_lut.csv
// Generated: 2026-02-09T22:52:04

#ifndef CONTROL_LQR_LUT_DATA_H
#define CONTROL_LQR_LUT_DATA_H

#define LQR_LUT_SIZE 7

static const float kHipLut[LQR_LUT_SIZE] = {
    -0.270000f,
    -0.162500f,
    -0.055000f,
    0.052500f,
    0.160000f,
    0.267500f,
    0.375000f,
};

static const float kLqrLut[LQR_LUT_SIZE][4] = {
    { -303592.298495f, -3918.490808f, 221.424988f, 587.006702f },
    { 347241.833263f, 7224.449375f, -220.474385f, -620.508006f },
    { 73311.258210f, 7916.578297f, -215.103856f, -416.202916f },
    { 61623.731487f, 6226.199116f, 219.396222f, 400.773911f },
    { 275840.945318f, 3541.230828f, 209.550014f, 510.283543f },
    { 374293.957151f, 2044.178314f, 221.389034f, 595.309414f },
    { 212380.818935f, 728.757615f, 166.811721f, 467.940788f },
};

static const float kThetaEq[LQR_LUT_SIZE] = {
    0.000000f,
    0.000000f,
    0.000000f,
    0.000000f,
    0.000000f,
    0.000000f,
    0.000000f,
};

static const float kUEq[LQR_LUT_SIZE] = {
    0.000000f,
    0.000000f,
    0.000000f,
    0.000000f,
    0.000000f,
    0.000000f,
    0.000000f,
};

#endif /* CONTROL_LQR_LUT_DATA_H */
